steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-west2-docker.pkg.dev/smart-axis421517/python-rss-reader/python-rss-reader:dev', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-west2-docker.pkg.dev/smart-axis421517/python-rss-reader/python-rss-reader:dev']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'jobs', 'create', 'python-rss-reader',
           '--image', 'us-west2-docker.pkg.dev/smart-axis421517/python-rss-reader/python-rss-reader:dev',
           '--region', 'us-west2']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['scheduler', 'jobs', 'create', 'http', 'python-rss-reader-scheduler',
           '--schedule', '0 * * * *',
           '--uri', 'https://us-west2-run.googleapis.com/apis/run.googleapis.com/v1/namespaces/smart-axis421517/jobs/python-rss-reader:run',
           '--http-method', 'POST',
           '--time-zone', 'UTC',
           '--oidc-service-account-email', 'general-purpose-account@smart-axis421517.iam.gserviceaccount.com']

timeout: '1200s'
